version: '3.9'

services:
  postgres:
    image: postgres:alpine3.18
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - 'postgres-db:/var/lib/postgresql/data'

  redis:
    image: redis:alpine3.18
    ports:
      - '${REDIS_PORT:-6379}:6379'
    environment:
      REDIS_PASSWORD: '${REDIS_PASSWORD}'
    volumes:
      - 'redis-db:/data'
      
volumes:
  postgres-db:
  redis-db:
