version: '3.9'

services:
  postgres:
    image: postgres:alpine3.18
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - 'postgres-db:/var/lib/postgresql/data'
volumes:
  postgres-db:
    driver: local
