// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	commondtos "lucio.com/order-service/src/domain/common/dtos"

	dtos "lucio.com/order-service/src/domain/customer/dtos"

	entities "lucio.com/order-service/src/domain/customer/entities"

	mock "github.com/stretchr/testify/mock"
)

// CreateCustomerUC is an autogenerated mock type for the CreateCustomerUC type
type CreateCustomerUC struct {
	mock.Mock
}

// Execute provides a mock function with given fields: customer
func (_m *CreateCustomerUC) Execute(customer entities.Customer) (*dtos.CreatedCustomerResponse, *commondtos.CustomError) {
	ret := _m.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dtos.CreatedCustomerResponse
	var r1 *commondtos.CustomError
	if rf, ok := ret.Get(0).(func(entities.Customer) (*dtos.CreatedCustomerResponse, *commondtos.CustomError)); ok {
		return rf(customer)
	}
	if rf, ok := ret.Get(0).(func(entities.Customer) *dtos.CreatedCustomerResponse); ok {
		r0 = rf(customer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CreatedCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.Customer) *commondtos.CustomError); ok {
		r1 = rf(customer)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*commondtos.CustomError)
		}
	}

	return r0, r1
}

// NewCreateCustomerUC creates a new instance of CreateCustomerUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCreateCustomerUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *CreateCustomerUC {
	mock := &CreateCustomerUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
