// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	dtos "lucio.com/order-service/src/domain/common/dtos"
	entities "lucio.com/order-service/src/domain/workorder/entities"

	mock "github.com/stretchr/testify/mock"
)

// EventRepository is an autogenerated mock type for the EventRepository type
type EventRepository struct {
	mock.Mock
}

// NotifyWorkOrderFinished provides a mock function with given fields: payload
func (_m *EventRepository) NotifyWorkOrderFinished(payload *entities.WorkOrder) *dtos.CustomError {
	ret := _m.Called(payload)

	if len(ret) == 0 {
		panic("no return value specified for NotifyWorkOrderFinished")
	}

	var r0 *dtos.CustomError
	if rf, ok := ret.Get(0).(func(*entities.WorkOrder) *dtos.CustomError); ok {
		r0 = rf(payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CustomError)
		}
	}

	return r0
}

// NewEventRepository creates a new instance of EventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRepository {
	mock := &EventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
