// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dtos "lucio.com/order-service/src/domain/common/dtos"
)

// FinishWorkOrderUC is an autogenerated mock type for the FinishWorkOrderUC type
type FinishWorkOrderUC struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ID
func (_m *FinishWorkOrderUC) Execute(ID string) *dtos.CustomError {
	ret := _m.Called(ID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *dtos.CustomError
	if rf, ok := ret.Get(0).(func(string) *dtos.CustomError); ok {
		r0 = rf(ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dtos.CustomError)
		}
	}

	return r0
}

// NewFinishWorkOrderUC creates a new instance of FinishWorkOrderUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinishWorkOrderUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinishWorkOrderUC {
	mock := &FinishWorkOrderUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
