// Code generated by mockery v2.30.16. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	dto "lucio.com/order-service/src/dto"
)

// UpdateCustomerUC is an autogenerated mock type for the UpdateCustomerUC type
type UpdateCustomerUC struct {
	mock.Mock
}

// Execute provides a mock function with given fields: updateCustomerDTO
func (_m *UpdateCustomerUC) Execute(updateCustomerDTO dto.UpdateCustomerDTO) (*dto.CustomerDTO, error) {
	ret := _m.Called(updateCustomerDTO)

	var r0 *dto.CustomerDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(dto.UpdateCustomerDTO) (*dto.CustomerDTO, error)); ok {
		return rf(updateCustomerDTO)
	}
	if rf, ok := ret.Get(0).(func(dto.UpdateCustomerDTO) *dto.CustomerDTO); ok {
		r0 = rf(updateCustomerDTO)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.CustomerDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(dto.UpdateCustomerDTO) error); ok {
		r1 = rf(updateCustomerDTO)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUpdateCustomerUC creates a new instance of UpdateCustomerUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateCustomerUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateCustomerUC {
	mock := &UpdateCustomerUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
